'use client';

import { Play, ChevronLeft, ChevronRight } from "lucide-react";
import { SectionHeading, HeroHeader, ExploreAnotherFuture } from "../Shared";

interface Props {
  goTo: (page: string) => void;
}

export default function AxisFlipPage({ goTo }: Props) {
  return (
    <>
      <HeroHeader 
        title="Axis Flip"
        description="A view from 2100 of the era in which Stanford flipped the axes of knowledge and competency."
        bgGradientClass="bg-[#461e68]"
      />
      <div className="max-w-5xl mx-auto px-6 py-16 space-y-24">
        
        <section className="space-y-6">
          <SectionHeading>The Summary</SectionHeading>
          <p className="text-sm text-gray-600">
            Take a look into archival footage returned from the future to discover how the university model was turned over by Axis Flip.
          </p>
          <div className="w-full aspect-video bg-gray-200 relative group cursor-pointer overflow-hidden max-w-4xl border border-gray-300">
            <img 
              src="https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=2500" 
              alt="Video Thumbnail" 
              className="w-full h-full object-cover filter grayscale opacity-70 group-hover:opacity-90 transition-opacity"
            />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-16 h-16 bg-black/60 rounded flex items-center justify-center text-white backdrop-blur-sm group-hover:bg-black/80 transition-colors">
                 <Play className="w-8 h-8 ml-1" />
              </div>
            </div>
          </div>
        </section>

        <section className="space-y-12">
          <div className="space-y-4">
            <SectionHeading>Historical Notes</SectionHeading>
            <hr className="border-t border-gray-200" />
          </div>

          <div className="grid md:grid-cols-2 gap-12">
            <div className="space-y-4">
              <h4 className="font-bold italic uppercase tracking-wider text-sm">The Setting</h4>
              <p className="font-bold italic text-sm text-gray-800 leading-relaxed">
                It was called the Crime of the Century. Ten days after the great 1906 earthquake, many of Stanford&apos;s historic buildings were piles of rubble. The wreckage revealed that contractors had taken unacceptable construction shortcuts. The University resolved that Stanford students would never again be left without a strong foundation.
              </p>
              <p className="text-sm text-gray-600 leading-relaxed">
                Over the next decade, Stanford re-built physically and academically. As one of the original pioneers of the undergraduate major system, Stanford organized its degrees around specific bodies of knowledge called departments. This major was again reinforced with general education requirements in 1920.
              </p>
            </div>
            <div className="space-y-4">
              <p className="text-sm text-gray-600 leading-relaxed">
                In the early 21st century, as information became ubiquitous and immediately referenceable, Stanford recognized that the role of the university as society&apos;s keeper of information was changing. At the same time, the volume of data and information being generated by humanity grew so quickly that new tools for analysis in virtually every field became essential. Traditional disciplines started to converge and then splinter into new areas of study at an unprecedented rate, and the integration of digital tools for data analysis rapidly altered the landscape of every academic department.
              </p>
              <h4 className="font-bold italic uppercase tracking-wider text-sm pt-4">Continued change</h4>
              <p className="text-sm text-gray-600 leading-relaxed">
                In 2012, a large, multi-disciplinary committee completed a detailed assessment of Stanford&apos;s educational offerings and issued the SUES report. The SUES report redefined the goals of a Stanford education: owning knowledge, honing skills and capacities, cultivating personal and social responsibility, and adaptive learning.
              </p>
            </div>
          </div>
        </section>

        <section className="space-y-12">
          <SectionHeading>The Shift</SectionHeading>
          <div className="grid md:grid-cols-2 gap-12">
            <div className="text-sm text-gray-600 leading-relaxed">
              <p>Starting in 2020, the University made a big bet on a new type of undergraduate focus that emphasized rigor around common and transferable skills to help interpret, navigate, and synthesize the growing world of information.</p>
              <p className="pt-4">Instead of building foundations solely in a unique discipline, students mastered skills and competencies, which became building blocks that could be &ldquo;rearranged&rdquo; and translated across a myriad of work contexts throughout their lifetimes.</p>
            </div>
            <div className="text-sm text-gray-600 leading-relaxed">
              <p>In 2024, Stanford launched undergrad teaching hubs built around ten competencies, with a Dean appointed to each. The Deans of Scientific Analysis, Quantitative Reasoning, Social Inquiry, Moral &amp; Ethical Reasoning, Aesthetic Interpretation, Creative Confidence, and Communication Effectiveness created physical hubs to which faculty co-located for periods of time to develop new courses and teach those courses.</p>
            </div>
          </div>
          
          <div className="grid md:grid-cols-2 gap-12 pt-8">
             <div className="space-y-4">
                <h4 className="font-bold italic uppercase tracking-wider text-sm text-gray-900">Unexpected Intersections</h4>
                <p className="text-sm text-gray-600 leading-relaxed">Early into this experiment, Stanford discovered that the most impactful courses were in the unexpected intersections (such as Social Inquiry + Computer Science or Quantitative Reasoning + History). Following an emerging pattern of interdisciplinary study, such as the early HCI, BioX and CS+ degrees, these fateful intersections of disciplines and competency hubs led to the creation of some of Stanford&apos;s most celebrated fields of study in the mid-21st century: Artificial Intelligence for Social Inquiry, Quantitative Global Affairs, and Right Brain Finance.</p>
                <p className="text-sm text-gray-600 leading-relaxed">Undergraduate teaching faculty were acclaimed for building a portfolio of courses that spanned the 10 competencies. Stanford PhD students, trained in course design using this approach, became the most highly sought-after junior faculty at top universities around the world.</p>
             </div>
             <div>
                <img src="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800" className="w-full h-full object-cover" alt="Hub map" />
             </div>
          </div>
        </section>

        <section className="space-y-8">
          <SectionHeading>The Achievement</SectionHeading>
          <div className="space-y-4 text-sm text-gray-600">
            <p>In Axis Flip:</p>
            <ul className="list-disc pl-5 space-y-2 leading-relaxed">
              <li>Stanford flipped the axes of knowledge and competencies so that skills became the independent variable of a Stanford education</li>
              <li>Students were given the building blocks to tackle any type of career in a rapidly changing economic landscape</li>
              <li>Undergraduate teaching hubs, each with a Dean at the center, became the University&apos;s organizing structure and central to its architecture</li>
              <li>Faculty collaborations spiked, and groundbreaking research accelerated when faculty were at residence in teaching hubs</li>
              <li>Transcripts were replaced by skill-prints</li>
            </ul>
            <p className="pt-4 font-bold italic">
               Stanford built a strong foundation in the Axis Flip era. Its original motto, &ldquo;the winds of freedom blow&rdquo; was amplified as graduates became known as agile navigators of an increasingly ambiguous world.
            </p>
          </div>
        </section>

      </div>
      <ExploreAnotherFuture currentPage="axis-flip" goTo={goTo} />
    </>
  );
}
