import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database with hypothetical data...\n');

  // ─── 10 Donations ───
  const donations = [
    { donorEmail: 'elena.vasquez@proton.me', donorName: 'Dr. Elena Vasquez', donorAnonymous: false, amount: 50000, currency: 'USD', paymentMethod: 'card', paymentStatus: 'completed', transactionRef: 'ART-1715280000-A1B2C3', perkId: 'founders-circle', isRecurring: false, recurringFreq: null, message: 'For the students who will change everything.' },
    { donorEmail: 'james.okonkwo@gmail.com', donorName: 'James & Priya Okonkwo', donorAnonymous: false, amount: 25000, currency: 'USD', paymentMethod: 'paypal', paymentStatus: 'completed', transactionRef: 'ART-1715193600-D4E5F6', perkId: 'guardians', isRecurring: true, recurringFreq: 'monthly', message: 'Investing in Africa\'s future scholars.' },
    { donorEmail: 'anonymous@proton.me', donorName: null, donorAnonymous: true, amount: 100000, currency: 'USD', paymentMethod: 'card', paymentStatus: 'completed', transactionRef: 'ART-1715107200-G7H8I9', perkId: 'chancellors', isRecurring: false, recurringFreq: null, message: 'Because knowledge should have no borders.' },
    { donorEmail: 'alrashidi@outlook.com', donorName: 'The Al-Rashidi Family', donorAnonymous: false, amount: 15000, currency: 'GBP', paymentMethod: 'card', paymentStatus: 'completed', transactionRef: 'ART-1715020800-J1K2L3', perkId: 'guardians', isRecurring: false, recurringFreq: null, message: 'In memory of Fatima Al-Rashidi, who believed in education for all.' },
    { donorEmail: 'finance@chenweilabs.cn', donorName: 'Chen Wei Labs', donorAnonymous: false, amount: 200000, currency: 'USD', paymentMethod: 'wire', paymentStatus: 'completed', transactionRef: 'ART-1714934400-M4N5O6', perkId: 'founders-circle', isRecurring: false, recurringFreq: null, message: null },
    { donorEmail: 'maria.santos@yahoo.com', donorName: 'Maria Santos', donorAnonymous: false, amount: 500, currency: 'USD', paymentMethod: 'card', paymentStatus: 'completed', transactionRef: 'ART-1714848000-P7Q8R9', perkId: null, isRecurring: true, recurringFreq: 'monthly', message: 'Proud to be part of the founding.' },
    { donorEmail: 't.yamamoto@keio.jp', donorName: 'Takeshi Yamamoto', donorAnonymous: false, amount: 1000, currency: 'USD', paymentMethod: 'card', paymentStatus: 'pending', transactionRef: 'ART-1714761600-S1T2U3', perkId: null, isRecurring: false, recurringFreq: null, message: null },
    { donorEmail: 'grants@nordgren.org', donorName: 'The Nordgren Foundation', donorAnonymous: false, amount: 500000, currency: 'USD', paymentMethod: 'wire', paymentStatus: 'completed', transactionRef: 'ART-1714675200-V4W5X6', perkId: 'chancellors', isRecurring: false, recurringFreq: null, message: 'Investing in the infrastructure of imagination.' },
    { donorEmail: 'amara.osei@ug.edu.gh', donorName: 'Amara Osei', donorAnonymous: false, amount: 100, currency: 'USD', paymentMethod: 'card', paymentStatus: 'completed', transactionRef: 'ART-1714588800-Y7Z8A9', perkId: null, isRecurring: false, recurringFreq: null, message: 'Every great university starts with a first believer.' },
    { donorEmail: 'info@liufang.cn', donorName: 'Liu Fang Foundation', donorAnonymous: false, amount: 75000, currency: 'USD', paymentMethod: 'wire', paymentStatus: 'pending', transactionRef: 'ART-1714502400-B1C2D3', perkId: 'guardians', isRecurring: true, recurringFreq: 'yearly', message: null },
  ];

  console.log('Creating 10 donations...');
  for (const d of donations) {
    await prisma.donation.create({ data: d });
  }

  // ─── 10 Applications ───
  const applications = [
    {
      firstName: 'Amina', lastName: 'Mohammed', email: 'amina.m@unilag.edu.ng', phone: '+234 801 234 5678', birthdate: '2004-03-15', gender: 'Female', pronoun: 'She/Her', citizenship: 'Nigeria', dualCitizenship: 'Ghana', address: '12 Admiralty Way', city: 'Lagos', state: 'Lagos', postalCode: '101234', country: 'Nigeria', howHeard: 'Social media', applicationCycle: '2026-Fall', concentration: 'Computational Sciences', currentlyEnrolled: 'Yes', schoolName: 'University of Lagos Secondary School', schoolCountry: 'Nigeria', schoolCity: 'Lagos', enrollmentStart: '2020-09', enrollmentEnd: '2026-06', gradingScale: '5.0', gpa: '4.7', maxGpa: '5.0', satMath: '780', satReading: '720', actScore: null, isTestOptional: false, accomplishments: JSON.stringify([{ title: 'National Science Olympiad', role: 'Team Captain', description: 'Led team to gold medal in national competition' }, { title: 'CodeLagos Hackathon', role: 'Winner', description: 'Built AI-powered agriculture monitoring tool' }]), personalStatement: 'Growing up in Lagos, I witnessed how access to technology transformed my community. I want to study computational sciences to build tools that solve real problems for real people across Africa and beyond.', missionStatement: 'I believe technology should serve humanity, not the other way around. My mission is to develop accessible AI systems that empower underserved communities.', applyingForAid: 'Yes', householdIncome: '$8,000', dependents: '3',
    },
    {
      firstName: 'Raj', lastName: 'Kapoor', email: 'raj.kapoor@iitb.ac.in', phone: '+91 98765 43210', birthdate: '2003-11-22', gender: 'Male', pronoun: 'He/Him', citizenship: 'India', dualCitizenship: null, address: '45 Marine Drive', city: 'Mumbai', state: 'Maharashtra', postalCode: '400020', country: 'India', howHeard: 'University website', applicationCycle: '2026-Fall', concentration: 'Philosophy & Ethics', currentlyEnrolled: 'Yes', schoolName: 'IIT Bombay Prep Academy', schoolCountry: 'India', schoolCity: 'Mumbai', enrollmentStart: '2019-07', enrollmentEnd: '2026-03', gradingScale: '10.0', gpa: '9.2', maxGpa: '10.0', satMath: '800', satReading: '750', actScore: '35', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'National Debate Championship', role: 'Finalist', description: 'Argued for universal access to higher education' }, { title: 'Mumbai Youth Council', role: 'Chair', description: 'Led policy recommendations on urban sustainability' }]), personalStatement: 'Philosophy is not an abstraction for me — it is the foundation upon which we build just societies. I seek to understand the ethical frameworks that should govern emerging technologies.', missionStatement: 'My mission is to bridge Eastern and Western philosophical traditions to develop ethical guidelines for artificial intelligence that respect cultural diversity.', applyingForAid: 'No', householdIncome: '$45,000', dependents: '0',
    },
    {
      firstName: 'Sofia', lastName: 'Andersen', email: 'sofia.a@uio.no', phone: '+47 912 34 567', birthdate: '2005-01-08', gender: 'Female', pronoun: 'She/Her', citizenship: 'Norway', dualCitizenship: 'Sweden', address: 'Storgata 23', city: 'Oslo', state: null, postalCode: '0184', country: 'Norway', howHeard: 'Academic counselor', applicationCycle: '2026-Fall', concentration: 'Environmental Systems', currentlyEnrolled: 'Yes', schoolName: 'Oslo Katedralskole', schoolCountry: 'Norway', schoolCity: 'Oslo', enrollmentStart: '2021-08', enrollmentEnd: '2026-06', gradingScale: '6.0', gpa: '5.8', maxGpa: '6.0', satMath: null, satReading: null, actScore: null, isTestOptional: true, accomplishments: JSON.stringify([{ title: 'Nordic Climate Research Program', role: 'Research Assistant', description: 'Studied permafrost degradation in Svalbard' }, { title: 'UN Youth Climate Summit', role: 'Delegate', description: 'Presented findings on Arctic ecosystem resilience' }]), personalStatement: 'The Arctic is warming four times faster than the rest of the planet, and my home is on the front lines. I want to study environmental systems to develop adaptive strategies for vulnerable ecosystems worldwide.', missionStatement: 'I aim to integrate indigenous ecological knowledge with modern environmental science to create sustainable conservation frameworks that work for both people and nature.', applyingForAid: 'No', householdIncome: '$72,000', dependents: '0',
    },
    {
      firstName: 'Carlos', lastName: 'Mendoza', email: 'carlos.m@unam.mx', phone: '+52 55 1234 5678', birthdate: '2004-07-30', gender: 'Male', pronoun: 'He/Him', citizenship: 'Mexico', dualCitizenship: 'United States', address: 'Av. Reforma 500', city: 'Mexico City', state: 'CDMX', postalCode: '06600', country: 'Mexico', howHeard: 'Family recommendation', applicationCycle: '2027-Spring', concentration: 'Urban Design & Architecture', currentlyEnrolled: 'No', schoolName: 'UNAM Prep School', schoolCountry: 'Mexico', schoolCity: 'Mexico City', enrollmentStart: '2019-08', enrollmentEnd: '2025-06', gradingScale: '10.0', gpa: '9.5', maxGpa: '10.0', satMath: '760', satReading: '690', actScore: '33', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'Mexican Architecture Biennale', role: 'Youngest Exhibitor', description: 'Designed community center for underserved neighborhood' }, { title: 'Habitat for Humanity Mexico', role: 'Volunteer Lead', description: 'Coordinated construction of 12 homes in Oaxaca' }]), personalStatement: 'Architecture is not just about buildings — it is about dignity. Growing up between two countries, I have seen how thoughtful design can transform communities and how neglect can destroy them.', missionStatement: 'My mission is to design spaces that heal communities, drawing from both ancient Mesoamerican principles and cutting-edge sustainable technology.', applyingForAid: 'Yes', householdIncome: '$22,000', dependents: '2',
    },
    {
      firstName: 'Yuki', lastName: 'Tanaka', email: 'yuki.tanaka@tokyo-u.ac.jp', phone: '+81 90-1234-5678', birthdate: '2004-05-14', gender: 'Non-binary', pronoun: 'They/Them', citizenship: 'Japan', dualCitizenship: null, address: '3-1-1 Hongo', city: 'Tokyo', state: 'Tokyo', postalCode: '113-0033', country: 'Japan', howHeard: 'Online article', applicationCycle: '2026-Fall', concentration: 'Neuroscience & Consciousness', currentlyEnrolled: 'Yes', schoolName: 'University of Tokyo Komaba', schoolCountry: 'Japan', schoolCity: 'Tokyo', enrollmentStart: '2022-04', enrollmentEnd: '2027-03', gradingScale: '4.0', gpa: '3.9', maxGpa: '4.0', satMath: '790', satReading: '740', actScore: '34', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'RIKEN Summer Research Program', role: 'Intern', description: 'Studied neural correlates of consciousness using fMRI' }, { title: 'Japan Science Olympiad', role: 'Gold Medalist', description: 'Biology division national champion' }, { title: 'Queer Youth Japan', role: 'Co-founder', description: 'Created support network for LGBTQ+ students in STEM' }]), personalStatement: 'Consciousness is the deepest mystery of our existence, and I believe understanding it requires both rigorous science and genuine empathy for the full spectrum of human experience.', missionStatement: 'I aim to advance our understanding of consciousness while ensuring that neuroscience research is inclusive and respectful of neurodiversity and gender diversity.', applyingForAid: 'No', householdIncome: '$68,000', dependents: '0',
    },
    {
      firstName: 'Fatou', lastName: 'Diallo', email: 'fatou.d@ucad.edu.sn', phone: '+221 77 123 4567', birthdate: '2005-09-03', gender: 'Female', pronoun: 'She/Her', citizenship: 'Senegal', dualCitizenship: 'France', address: 'Rue 10, Fann Hock', city: 'Dakar', state: null, postalCode: '10100', country: 'Senegal', howHeard: 'Community organization', applicationCycle: '2026-Fall', concentration: 'Public Health & Medicine', currentlyEnrolled: 'Yes', schoolName: 'Lycée Mariama Bâ', schoolCountry: 'Senegal', schoolCity: 'Saint-Louis', enrollmentStart: '2020-10', enrollmentEnd: '2026-07', gradingScale: '20.0', gpa: '17.5', maxGpa: '20.0', satMath: null, satReading: null, actScore: null, isTestOptional: true, accomplishments: JSON.stringify([{ title: 'WHO Youth Health Ambassador', role: 'Ambassador', description: 'Led malaria prevention campaign reaching 10,000 families' }, { title: 'Senegal National Math Competition', role: 'Top 5 Finalist', description: 'Highest-scoring female participant' }]), personalStatement: 'I have seen malaria take lives in my community that could have been saved with better infrastructure and education. Public health is not just a career for me — it is a calling born from loss and hope.', missionStatement: 'My mission is to develop community-driven health systems that combine traditional Senegalese healing practices with modern evidence-based medicine.', applyingForAid: 'Yes', householdIncome: '$5,500', dependents: '5',
    },
    {
      firstName: 'Liam', lastName: "O'Brien", email: 'liam.obrien@tcd.ie', phone: '+353 87 123 4567', birthdate: '2004-12-25', gender: 'Male', pronoun: 'He/Him', citizenship: 'Ireland', dualCitizenship: null, address: '42 Grafton Street', city: 'Dublin', state: 'Leinster', postalCode: 'D02', country: 'Ireland', howHeard: 'Teacher recommendation', applicationCycle: '2027-Spring', concentration: 'Comparative Literature', currentlyEnrolled: 'Yes', schoolName: 'Trinity College Dublin Foundation', schoolCountry: 'Ireland', schoolCity: 'Dublin', enrollmentStart: '2021-09', enrollmentEnd: '2027-06', gradingScale: '4.0', gpa: '3.8', maxGpa: '4.0', satMath: '700', satReading: '790', actScore: '32', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'Irish Young Playwright Award', role: 'Winner', description: 'Wrote play exploring identity in post-Brexit Ireland' }, { title: 'College Literary Magazine', role: 'Editor-in-Chief', description: 'Published quarterly magazine with 2,000+ readers' }]), personalStatement: 'Stories are how we make sense of a world that often does not make sense. Through comparative literature, I want to trace the threads that connect Irish oral tradition with West African griot storytelling and find what they reveal about our shared humanity.', missionStatement: 'I aim to preserve and celebrate oral storytelling traditions while making them accessible to new audiences through digital media and cross-cultural collaboration.', applyingForAid: 'No', householdIncome: '$55,000', dependents: '1',
    },
    {
      firstName: 'Zara', lastName: 'Al-Hussein', email: 'zara.h@ju.edu.jo', phone: '+962 7 9123 4567', birthdate: '2004-02-18', gender: 'Female', pronoun: 'She/Her', citizenship: 'Jordan', dualCitizenship: 'Palestine', address: 'Al-Weibdeh, Sharia 7', city: 'Amman', state: 'Amman', postalCode: '11181', country: 'Jordan', howHeard: 'Social media', applicationCycle: '2026-Fall', concentration: 'International Law & Human Rights', currentlyEnrolled: 'Yes', schoolName: 'University of Jordan Preparatory', schoolCountry: 'Jordan', schoolCity: 'Amman', enrollmentStart: '2020-09', enrollmentEnd: '2026-06', gradingScale: '100', gpa: '94', maxGpa: '100', satMath: '740', satReading: '770', actScore: '33', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'Model UN Secretary General', role: 'SG', description: 'Led 500-delegate conference on refugee rights' }, { title: 'UNHCR Youth Volunteer', role: 'Volunteer', description: 'Documented legal challenges facing Syrian refugees in Jordan' }, { title: 'Arabic Debate League', role: 'Champion', description: 'Undefeated in national debate competition' }]), personalStatement: 'As a Palestinian-Jordanian, I have lived the consequences of international legal frameworks that fail the most vulnerable. I am determined to strengthen the systems that protect displaced people worldwide.', missionStatement: 'My mission is to reform international refugee law to create binding obligations that prioritize human dignity over political convenience.', applyingForAid: 'Yes', householdIncome: '$14,000', dependents: '4',
    },
    {
      firstName: 'Kwame', lastName: 'Asante', email: 'kwame.a@ug.edu.gh', phone: '+233 24 567 8901', birthdate: '2003-08-11', gender: 'Male', pronoun: 'He/Him', citizenship: 'Ghana', dualCitizenship: null, address: 'University of Ghana Campus', city: 'Accra', state: 'Greater Accra', postalCode: 'GA-123', country: 'Ghana', howHeard: 'Alumni network', applicationCycle: '2027-Spring', concentration: 'Economics & Development', currentlyEnrolled: 'No', schoolName: 'Presbyterian Boys Senior High', schoolCountry: 'Ghana', schoolCity: 'Accra', enrollmentStart: '2018-09', enrollmentEnd: '2024-06', gradingScale: '4.0', gpa: '3.6', maxGpa: '4.0', satMath: '710', satReading: '660', actScore: '30', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'Ghana Innovation Challenge', role: 'Co-founder', description: 'Created mobile banking solution for rural farmers' }, { title: 'National Youth Parliament', role: 'Member', description: 'Drafted policy recommendations on digital financial inclusion' }]), personalStatement: 'I grew up watching my grandmother walk 12 kilometers to reach a bank. Financial exclusion is not just an inconvenience — it is a barrier to human potential. Economics, for me, is about removing that barrier.', missionStatement: 'My mission is to design economic systems and financial tools that serve the unbanked and underbanked populations of Sub-Saharan Africa, leveraging mobile technology and community trust networks.', applyingForAid: 'Yes', householdIncome: '$6,200', dependents: '6',
    },
    {
      firstName: 'Elena', lastName: 'Petrov', email: 'elena.p@hse.ru', phone: '+7 916 123 4567', birthdate: '2004-06-20', gender: 'Female', pronoun: 'She/Her', citizenship: 'Russia', dualCitizenship: 'Germany', address: 'ul. Myasnitskaya 20', city: 'Moscow', state: 'Moscow', postalCode: '101000', country: 'Russia', howHeard: 'Academic conference', applicationCycle: '2026-Fall', concentration: 'Quantum Computing', currentlyEnrolled: 'Yes', schoolName: 'Moscow State University Lyceum', schoolCountry: 'Russia', schoolCity: 'Moscow', enrollmentStart: '2021-09', enrollmentEnd: '2027-06', gradingScale: '5.0', gpa: '4.9', maxGpa: '5.0', satMath: '800', satReading: '710', actScore: '35', isTestOptional: false, accomplishments: JSON.stringify([{ title: 'International Physics Olympiad', role: 'Silver Medalist', description: 'Solved quantum mechanics problems at IPHO 2024' }, { title: 'Russian Quantum Center Intern', role: 'Research Intern', description: 'Developed quantum error correction algorithm for NISQ devices' }]), personalStatement: 'Quantum computing will redefine what is computationally possible, and I want to be at the frontier of this revolution — not just as a researcher, but as someone who ensures these powerful tools benefit all of humanity.', missionStatement: 'I aim to develop practical quantum algorithms that solve real-world optimization problems, while working to make quantum education accessible to students in developing nations.', applyingForAid: 'No', householdIncome: '$38,000', dependents: '0',
    },
  ];

  console.log('Creating 10 applications...');
  for (const a of applications) {
    await prisma.application.create({ data: a });
  }

  // ─── 10 Contact Messages ───
  const messages = [
    { name: 'David Chen', email: 'david.chen@techcorp.io', subject: 'Partnership Inquiry', area: 'Partnerships', message: 'I represent a technology company interested in partnering with the University of Artemis on AI research. We would like to explore opportunities for joint research programs and student internships. Could we schedule a call to discuss potential collaboration frameworks?', read: true },
    { name: 'Sarah Williams', email: 'sarah.w@gmail.com', subject: 'Scholarship Information', area: 'Admissions', message: 'My daughter is interested in applying for the 2026 Fall cycle. Could you provide more details about the financial aid options available for international students from the Caribbean? We want to understand the full scope of support before submitting an application.', read: false },
    { name: 'Ahmed Hassan', email: 'ahmed.h@un.org', subject: 'UNESCO Collaboration', area: 'Partnerships', message: 'I work with UNESCO\'s higher education division. We are very impressed by the Artemis model and would like to explore how our organizations might collaborate on making quality education accessible in conflict-affected regions. We have funding available for innovative educational partnerships.', read: true },
    { name: 'Maria Torres', email: 'maria.torres@alumni.harvard.edu', subject: 'Faculty Position Inquiry', area: 'General Enquiry', message: 'I am a professor of comparative literature with 15 years of teaching experience. The University of Artemis vision deeply resonates with me. Are there any faculty positions available, and if so, what is the application process? I would love to contribute to building this institution.', read: false },
    { name: 'James Okello', email: 'james.okello@uganda.co.ug', subject: 'Community Outreach', area: 'Community', message: 'I lead a youth empowerment organization in Kampala, Uganda. We would like to explore how our 500+ students might benefit from Artemis programs. Is there a community outreach or pre-university pipeline program we could participate in?', read: true },
    { name: 'Priya Sharma', email: 'priya.sharma@investor.com', subject: 'Endowment Opportunity', area: 'Donations', message: 'Our family foundation is interested in making a significant endowment to support STEM education at Artemis. We would like to understand the named endowment options and the impact our contribution could have. What is the minimum endowment size for naming a research center?', read: false },
    { name: 'Tom Richardson', email: 'tom.r@journalist.com', subject: 'Media Coverage Request', area: 'General Enquiry', message: 'I am a journalist with The Guardian covering innovations in higher education. I would like to write a feature about the University of Artemis. Could I arrange an interview with the founding team and visit the campus (or virtual campus) to learn more?', read: true },
    { name: 'Liu Wei', email: 'liu.wei@tsinghua.edu.cn', subject: 'Student Exchange Program', area: 'Partnerships', message: 'I am the director of international programs at Tsinghua University. We are interested in establishing a student exchange agreement with the University of Artemis. Our students could benefit greatly from the interdisciplinary approach you are pioneering. How do we begin this conversation?', read: false },
    { name: 'Grace Nakamura', email: 'grace.n@alumni.stanford.edu', subject: 'Mentorship Program', area: 'Community', message: 'As a Stanford alumna working in Silicon Valley, I would love to mentor Artemis students who are interested in technology entrepreneurship. Do you have a mentorship program, and if not, could I help you establish one? I can also recruit other mentors from my network.', read: true },
    { name: 'Roberto Silva', email: 'roberto.s@unesco.org', subject: 'Accreditation Process', area: 'Admissions', message: 'I am following up on the accreditation status of the University of Artemis. As a prospective student from Brazil, I need to ensure that my degree will be recognized internationally. Could you share any updates on the accreditation timeline and which bodies you are working with?', read: false },
  ];

  console.log('Creating 10 contact messages...');
  for (const m of messages) {
    await prisma.contactMessage.create({ data: m });
  }

  // ─── 10 Subscribers ───
  const subscribers = [
    { email: 'newsletter.fan@proton.me', source: 'homepage', active: true },
    { email: 'alex.kumar@gmail.com', source: 'blog', active: true },
    { email: 'dr.patricia.wong@harvard.edu', source: 'footer', active: true },
    { email: 'student.hope@yahoo.com', source: 'homepage', active: true },
    { email: 'sustainable.future@outlook.com', source: 'give', active: true },
    { email: 'omar.farouk@cairo.edu.eg', source: 'blog', active: true },
    { email: 'innovation.seeker@tech.io', source: 'homepage', active: false },
    { email: 'lena.schmidt@tu-berlin.de', source: 'footer', active: true },
    { email: 'global.citizen@un.org', source: 'give', active: true },
    { email: 'future.scholar@artemisui.org', source: 'blog', active: true },
  ];

  console.log('Creating 10 subscribers...');
  for (const s of subscribers) {
    await prisma.subscriber.upsert({
      where: { email: s.email },
      update: {},
      create: s,
    });
  }

  console.log('\n✅ Seed completed: 10 donations, 10 applications, 10 messages, 10 subscribers');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
